export enum IdentificationTypeEnum {
  CC = 'CÉDULA DE CIUDADANÍA',
  CE = 'CÉDULA DE ENTRANJERÍA',
  RESIDENCE_ID = 'DOCUMENTO DE RESIDENCIA',
  NIT = 'NIT',
  DNI = 'DOCUMENTO NACIONAL DE IDENTIDAD',
  PASSPORT = 'PASAPORTE',
  DRIVER_LICENSE = 'LICENCIA DE CONDUCCIÓN',
  OTHER = 'OTRO',
}
